### ISSUE TITLE
Don't require authorization for deployments

### ISSUE THREAD

**Issue by shubham-saudolla** [zeit/hyper-site#119]
The now bot has failed my pull request due to lack of authorization.
How do I create a valid pull request?
Regarding pull request #118

**Comment by davidleininger** [comment]
Same for mine: #139 

This is a duplicate issue of #110

**Comment by ivoilic** [comment]
@timothyis Seems like there a few PRs waiting due to lack of authorization!

**Comment by timothyis** [comment]
You're absolutely right @ivoilic, I apologise for the lack of response on this repository as of late. As you might have seen, we've been really busy focusing on pushing a bunch of great features for ZEIT Now (https://zeit.co/blog), so we've not had a lot of opportunities to focus a lot on hyper-site. I've just put together a few people that will help me maintain this in the future though, so we'll be starting to pick this up.

On the subject of this issue, the reason PRs need authorization is that we use a GitHub auth token to bypass a rate limit when pinging their API. Because of this GitHub token, which we store as a Now Secret, Now for GitHub requires authorization as a security measure.
I'm working on a way, as we speak, to bypass this 🙌.

Thanks all for creating an issue and pinging to make sure we get back to this. We're really proud of Hyper and its community.

As a side note; if anyone would like to join the ZEIT Slack to help maintain this or Hyper, let me know and I'll invite you to a channel for Hyper maintainers. We'd love to have anyone interested in helping, join us and contribute.

**Comment by timothyis** [comment]
Looks like someone has already made the change needed by caching the response! So I'll just remove the secret all together 🙏

**Comment by ivoilic** [comment]
@timothyis I'll take you up on that offer to join the ZEIT Slack. You can reach me [here](https://twitter.com/TheIvoSon) if you want me to DM my email etc.

**Comment by davidleininger** [comment]
@timothyis same here. I'll never turn down that offer. [Twitter](https://twitter.com/davidleininger) or DM for my email. Thanks!

**Comment by davidleininger** [comment]
@timothyis Is there anything we need to do to get our PR's through?

**Comment by timothyis** [comment]
I'll make sure to set aside some time this week to review and merge all PRs. Thanks again for the ping @davidleininger.

**Comment by timothyis** [comment]
Just an update here. I've been reviewing the PRs, however, there seems to be an issue with the API we use to pull information about npm packages where it is not listing the packages properly and ends up errorring when trying to show the information on hyper-site. I'm trying to look into it. I'll get back to you all soon. 🙏

**Comment by pacocoursey** [comment]
Should be good now!
